version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1.6

executors:
  postgres:
    docker:
      - image: "circleci/postgres:12"
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: super-secret
          POSTGRES_DB: nhs_visit
  cypress:
    docker:
      - image: "cypress/base:12.16.1"
        environment:
          URI: postgres://circleci:super-secret@localhost/nhs_visit
          ALLOWED_CODES: TESTCODE,VALIDCODE
          JWT_SIGNING_KEY: signing_key

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm rebuild node-sass
            - run: npm run test:ci
            - run: npm run build

workflows:
  build:
    jobs:
      - build-and-test
      - cypress/install:
          build: "npm run build" # run a custom app build step
      - cypress/run:
          executor: postgres
          requires:
            - cypress/install
          command: "psql nhs_visit < ~/db/schema.sql"
      - cypress/run:
          executor: cypress
          requires:
            - cypress/install
          group: "all tests" # name this group "all tests" on the dashboard
          start: "npm run dev" # start server before running tests
          store_artifacts: true
